controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    princess.stopDart()
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    princess.throwDart()
})
let princess: Dart = null
scene.setBackgroundColor(3)
princess = darts.create(img`
    . . . . . . f f f f 4 4 f . . . 
    . . . . f f b f 5 4 5 5 4 f . . 
    . . . f b 3 3 e 4 5 5 5 5 f . . 
    . . f b 3 3 3 3 e 4 4 4 e f . . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . . f 3 3 3 3 e b 3 e e 3 3 f . 
    . . f 3 3 3 3 f f e e e 3 3 f . 
    . . f b b b b f b f e e e 3 f . 
    . . f b b b b e 1 f 4 4 e f . . 
    . f f b b b b f 4 4 4 4 f . . . 
    . f b b b b f f f e e e f . . . 
    . . f b b f 4 4 e d d d f . . . 
    . . . f f e 4 4 e d d d f . . . 
    . . . . f b e e b d b d b f . . 
    . . . . f f d 1 d 1 d 1 f f . . 
    . . . . . . f f b b f f . . . . 
    `, SpriteKind.Player)
princess.setTrace()
princess.controlWithArrowKeys()
let Castle = sprites.create(img`
    ................................................
    ................................................
    ................................................
    ......................cb........................
    .....................bcbb.......................
    ....................cbcbbc......................
    ...................bcccbbcc........1............
    .........11.......bbcbcbbcbc.......11...........
    ........111......cbbcbcbbcbcb......111..........
    .......1111.....bccccbcbbcbccc.....1111.........
    ......11111....cccbbcbcbbcbcbbc....e............
    ..........e....bbcbbcccbbcccbbcb...e............
    ..........e...cbbcbbcbcbbcbcbbcbb..e............
    ..........e..bcbbcbbcbcbbcbcbbcbbc.e............
    ..........e.bbcbbcbbcbcbbcbcbbcbbcbe............
    ..........ecbbcbbccccbcbbcbccccbbcbe............
    ..........bcbbccccbbcccbbcccbbccccbb............
    ..........bccccbbcbbcbcbbcbcbbcbbcccc...........
    .........bbcbbcbbcbbcbcbbcbcbbcbbcbbc...........
    ........ccccbbcbbcbbcbcbbcbcbbcbbcbbcc..........
    ........cbbcbbcbbcbbcccbbcccbbcbbcbbcbb.........
    .......ccbbcbbcbbcccccbbbbcccccbbcbbcbbc........
    .......bcbbcbbcccccbbbbbbbbbbcccccbbcbbcb.......
    ......bbcbbcccccbbbbbccccccbbbbbcccccbbcbb......
    ......bbcccccbbbbbccbddddddbccbbbbbcccccbb......
    ......bbccbbbbbccbddddddddddddbccbbbbbccbb......
    ......cbbbbcccbddddddddddddddddddbcccbbbbc......
    ......bbcccbdddbccbbbbbbbbbbbbccbdddbcccbb......
    ......ccbbbbbbbcbddddddddddddddbcbbbbbbbcc......
    ......dddddddbcddddddddddddddddddcbddddddd......
    ......dddddddcbd1111111111111111dbcddddddd......
    ......ccccccccd1dddddddddddddddd1dcccccccc......
    ......dddddddc11dbbbbbbbbbbbbbbd11cddddddd......
    ......bbbbbfdc1dbbb33b33b33b33bbd1cdfbbbbb......
    ......ffffffdc1dbbb33b33b33b33bbd1cdffffff......
    ......bbbbbfdcddfbb3ebbbbbbe33bbddcdfbbbbb......
    ......fbffbfdcddfbbbbbbbbbbbb3bbddcdfbffbf......
    ......cbccbfdcddfbbbbbbbbbbbbbbbddcdfbccbc......
    ......bbbbbfdcddfbbbbbbbbbbbbbbbddcdfbbbbb......
    ......fbffbfdcddbbb33b33b33b33bbddcdfbffbf......
    ......cbccbfdcddbbb33b33b33b33bbddcdfbccbc......
    ......bbbbbbdcddbbb33b33b33bbbbbddcdbbbbbb......
    ......dddddddcddbbb33b33b33bbbbbddcddddddd......
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    `, SpriteKind.Player)
Castle.setPosition(142, 24)
